# This is a file of Task 3

Doing various Operations using Numpy

In [4]:
import numpy as np

# 1. Creating 1D arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 4, 3, 2, 1])
print("1. arr1:", arr1)
print("arr2:", arr2)

1. arr1: [10 20 30 40 50]
arr2: [5 4 3 2 1]


In [3]:
# 2. Creating 2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("2. 2D array arr3:\n", arr3)

2. 2D array arr3:
 [[1 2 3]
 [4 5 6]]


In [5]:
# 3. Shape of array
print("3. Shape of arr3:", arr3.shape)

3. Shape of arr3: (2, 3)


In [6]:
# 4. Size of array
print("4. Size of arr1:", arr1.size)

4. Size of arr1: 5


In [8]:
# 5. Reshaping arr1 to 5x1
arr1_reshaped = arr1.reshape((5,1))
print("5. arr1 reshaped to (5,1):\n", arr1_reshaped)

5. arr1 reshaped to (5,1):
 [[10]
 [20]
 [30]
 [40]
 [50]]


In [9]:
# 6. Access element
print("6. Element at arr3[1,2]:", arr3[1,2])

6. Element at arr3[1,2]: 6


In [10]:
# 7. Slicing
print("7. Slice arr1 first 3 elements:", arr1[:3])

7. Slice arr1 first 3 elements: [10 20 30]


In [11]:
# 8. Arithmetic operations (addition)
print("8. arr1 + arr2 =", arr1 + arr2)

8. arr1 + arr2 = [15 24 33 42 51]


In [12]:
# 9. Arithmetic operations (multiplication)
print("9. arr1 * arr2 =", arr1 * arr2)

9. arr1 * arr2 = [50 80 90 80 50]


In [13]:
# 10. Broadcasting (arr1 + scalar)
print("10. arr1 + 100 =", arr1 + 100)

10. arr1 + 100 = [110 120 130 140 150]


In [15]:
# 11. Sum of arr1
print("11. Sum of arr1:", np.sum(arr1))

11. Sum of arr1: 150


In [16]:
# 12. Mean of arr2
print("12. Mean of arr2:", np.mean(arr2))

12. Mean of arr2: 3.0


In [18]:
# 13. Median of arr1
print("13. Median of arr1:", np.median(arr1))

13. Median of arr1: 30.0


In [19]:
# 14. Standard deviation
print("14. Standard deviation of arr1:", np.std(arr1))

14. Standard deviation of arr1: 14.142135623730951


In [21]:
# 15. Sort arr2
print("15. Sorted arr2:", np.sort(arr2))

15. Sorted arr2: [1 2 3 4 5]


In [22]:
# 16. Transpose of arr3
print("16. Transpose of arr3:\n", arr3.T)

16. Transpose of arr3:
 [[1 4]
 [2 5]
 [3 6]]


In [23]:
# 17. Create zeros array
zeros_arr = np.zeros((2,3))
print("27. Zeros array (2x3):\n", zeros_arr)

27. Zeros array (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# 18. Create identity matrix
identity = np.eye(3)
print("18. Identity matrix (3x3):\n", identity)

18. Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
